### ISSUE TITLE
Implement the file generation

### ISSUE THREAD

**Issue by illright** [feature-sliced/cli#2]
Implement a function that takes the output of #1 and a resolved path to the single FSD root and generates the files according to the [specification](https://feature-sliced.notion.site/File-generator-CLI-7e55130e6bc24a21975443b5493ac989?pvs=4).

The shape of the function is:
```ts
async function generateFiles(
  request: CreationRequest, 
  fsdRoot: string,
  isTypeScript = false,
): Promise<void>;
```

Place the function in `src/generate-files.ts` and cover it with unit tests.

**Comment by AgentRBY** [comment]
Implemented by me in #5
