### ISSUE TITLE
Implement TypeScript detection

### ISSUE THREAD

**Issue by illright** [feature-sliced/cli#3]
According to the [specification](https://feature-sliced.notion.site/File-generator-CLI-7e55130e6bc24a21975443b5493ac989?pvs=4), implement a function that traverses the files in search of `package.json` and `tsconfig.json` and uses that information to return a Boolean value of whether the project is using TypeScript or not.

The shape of a function is:
```ts
async function isTypeScriptInProject(): Promise<boolean> {}
```

Place the function in `src/is-typescript-in-project.ts`. Cover the function with unit tests.

**Comment by AgentRBY** [comment]
Implemented by me in #5
