### ISSUE TITLE
Implement FSD root detection

### ISSUE THREAD

**Issue by illright** [feature-sliced/cli#4]
According to the [specification](https://feature-sliced.notion.site/File-generator-CLI-7e55130e6bc24a21975443b5493ac989?pvs=4) of the tool, implement the detection of FSD roots that should be generated in. If there are multiple candidates, return an array of paths to each candidate.

The detection should be done with a function of the following shape:
```ts
async function detectFsdRoot(): Promise<string | Array<string>>;
```

Place the function in `src/detect-fsd-root.ts`. Cover the function with unit tests.

**Comment by AgentRBY** [comment]
Implemented by me in #5
